### PR TITLE
Use paragraph names specific to LocalGov Drupal

### LINKED ISSUE #7: Add custom LinkIt plugin usage instruction in README
This module has a [custom LinkIt plugin](https://github.com/localgovdrupal/localgov_page_components/tree/master/src/Plugin/Linkit) for inserting URLs from LocalGov Link and LocalGov Contact-based paragraph library items (AKA Page components).  For this to work, the plugin has to be added to a LinkIt **profile**.  The usage instruction should cover the process.

### PR DESCRIPTION
**Pull request by Adnan-cds**
Update paragraph names to those from the LocalGov Drupal codebase.  Previously
it was using paragraphs names from the BHCC/Croydon codebase.

~**Todo**: Needs tests~

### CODE REVIEW

**Comment by andybroomfield** [comment]
This might also require an update hook to move content to the new names @Adnan-cds

**Comment by Adnan-cds** [comment]
Hi Andy,
The Paragraph names actually haven't changed.  It's that the LinkIt plugin is referring to names used in the BHCC/Croydon codebase.  For example, it is looking for [advanced_links paragraphs](https://github.com/localgovdrupal/localgov_page_components/blob/024490f5d7ab7365f256f4f41546078994ac046b/src/Plugin/Linkit/Substitution/ParagraphsLibraryItem.php#L51) even though in LocalGov, this paragraph is called localgov_link.  This change just fixes these names.

**Comment by Adnan-cds** [comment]
Ready for review and testing.  I have added LinkIt integration instructions in the README.

**Comment by ekes** [comment]
This is all test right? 
Except for updating src/Plugin/Linkit/Substitution/ParagraphsLibraryItem.php which aligns the fieldnames elsewhere?
So this would want to go in before we tag a 1.0.0 release?

**Comment by Adnan-cds** [comment]
> This is all test right?
> Except for updating src/Plugin/Linkit/Substitution/ParagraphsLibraryItem.php which aligns the fieldnames elsewhere?

That's right.

 > So this would want to go in before we tag a 1.0.0 release?

That would be good.

**Comment by stephen-cox** [comment]
Hi @Adnan-cds, Just trying to get my head around this.

If I follow the instructions in the README for Linkit integration, I can create a link paragraph and the link paragraph appears in the the WYSIWYG link widget, but it links to the admin paragraph display. Is this desired behaviour?

**Comment by Adnan-cds** [comment]
> I can create a link paragraph and the link paragraph appears in the the WYSIWYG link widget, but it links to the admin paragraph display. Is this desired behaviour?

Thanks for looking into this Steve :)  If you please save the page, the URL of the admin paragraph display should turn into the URL pointed to by the Link Page component unless I have misunderstood what you are seeing.  That happens when you link to nodes too.  That's how LinkIt works AFAIK.

**Comment by stephen-cox** [comment]
OK, the issue was me not following your instructions properly :roll_eyes:  Seems to work once configured properly. One improvement would be to apply the Linkit configuration when installing the module.

**Review by stephen-cox — APPROVED** [review]

**Comment by Adnan-cds** [comment]
> One improvement would be to apply the Linkit configuration when installing the module.

Sounds like a good idea.  I will add a ticket.  Thanks for the approval.

**Comment by ekes** [comment]
So I'll merge this. Tag one more release and the we can go #12

**Pull request merged**
