### PR TITLE
Chore: Unneeded patch

### PR DESCRIPTION
**Pull request by Adnan-cds**
Removing unneeded patch which has been accepted by the entity_browser recently.

@see https://www.drupal.org/node/3130500

### CODE REVIEW

**Comment by ekes** [comment]
The patch [introduced here](https://github.com/localgovdrupal/localgov_page_components/commit/3ed828ba27bff1d6531af7e8a679f847bd3e0a41) seems to be [applied to 2.x](https://www.drupal.org/project/entity_browser/issues/3130500#comment-14580851) we still seem to be using [1.x](https://github.com/localgovdrupal/localgov_page_components/blob/1.x/composer.json#L10)? I'd guess we want to be on 2.x mind.

**Comment by Adnan-cds** [comment]
Err... we are using [entity_browser:2.x](https://github.com/localgovdrupal/localgov_page_components/blob/90dce20dcb9c105ee258c79cb8ac6d9465cdaf2d/composer.json#L9) and [inline_entity_form:1.x](https://github.com/localgovdrupal/localgov_page_components/blob/1.x/composer.json#L10).  The patch was for entity_browser.  So looks okay, no?

**Review by ekes — APPROVED** [review]
You're right looking at the wrong module. This is in entity_browser 2.x as described.

**Comment by Adnan-cds** [comment]
Thanks for the approval.  Merging...

**Pull request merged**
